# Generated by Django 3.1.2 on 2020-11-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lock',
            name='door',
        ),
        migrations.RemoveField(
            model_name='record',
            name='door',
        ),
        migrations.AlterField(
            model_name='lock',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
